//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissbotCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissbotCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      body {
        ///        font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto,
        ///          Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;,
        ///          &quot;Segoe UI Symbol&quot;;
        ///      }
        ///      @keyframes close {
        ///        from {
        ///          transform: rotate(-90deg);
        ///        }
        ///        to {
        ///          transform: rotate(0);
        ///        }
        ///      }
        ///      @keyframes open {
        ///        from {
        ///          transform: rotate(0);
        ///        }
        ///        to {
        ///          tran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string listingTickets {
            get {
                return ResourceManager.GetString("listingTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      body {
        ///        font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto,
        ///          Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;,
        ///          &quot;Segoe UI Symbol&quot;;
        ///        background-color: #36393f;
        ///        display: flex;
        ///        justify-content: center;
        ///        color: white;
        ///        text-align: center;
        ///      }
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div class=&quot;content&quot;&gt;
        ///      &lt;h1&gt;You have been logged out!&lt;/h1&gt;
        ///      &lt;h4&gt;Btw you are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loggedOut {
            get {
                return ResourceManager.GetString("loggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      body {
        ///        font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto,
        ///          Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;,
        ///          &quot;Segoe UI Symbol&quot;;
        ///      }
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body style=&quot;background-color: #36393f&quot;&gt;
        ///    &lt;div
        ///      class=&quot;content&quot;
        ///      style=&quot;
        ///        display: flex;
        ///        align-items: center;
        ///        flex-direction: column;
        ///        color: white;
        ///      &quot;
        ///    &gt;
        ///      &lt;img
        ///        style=&quot;w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notLoggedIn {
            get {
                return ResourceManager.GetString("notLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div
        ///  class=&quot;item&quot;
        ///  style=&quot;
        ///    display: flex;
        ///    color: white;
        ///    margin-left: 1rem;
        ///    background-color: #2c2f33;
        ///    border-radius: 2rem;
        ///    margin-top: 1rem;
        ///    width: 100%;
        ///    align-items: center;
        ///  &quot;
        ///&gt;
        ///  &lt;img
        ///    src=&quot;{item.profile}&quot;
        ///    aria-hidden=&quot;true&quot;
        ///    alt=&quot;&quot;
        ///    style=&quot;
        ///      margin-left: 0.75rem;
        ///      width: 50px;
        ///      height: 50px;
        ///      border-radius: 50%;
        ///      overflow: hidden;
        ///      cursor: pointer;
        ///      -webkit-user-select: none;
        ///      -moz-user-sele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ticketItem {
            get {
                return ResourceManager.GetString("ticketItem", resourceCulture);
            }
        }
    }
}
