//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissbotCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissbotCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt; &lt;/head&gt;
        ///  &lt;body style=&quot;background-color: #36393f&quot;&gt;
        ///    &lt;div
        ///      class=&quot;header&quot;
        ///      style=&quot;
        ///        border-bottom: 1px white dashed;
        ///        padding-bottom: 1rem;
        ///        text-align: center;
        ///        color: white;
        ///        padding-top: 1rem;
        ///        position: sticky;
        ///        top: 0px;
        ///        background-color: inherit;
        ///        z-index: 10;
        ///        display: flex;
        ///        align-items: center;
        ///        justify-content: center;
        ///      &quot;
        ///    &gt;
        ///      &lt;h1 style=&quot;width: 70%&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string listingTickets {
            get {
                return ResourceManager.GetString("listingTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div
        ///  class=&quot;item&quot;
        ///  style=&quot;
        ///    display: flex;
        ///    color: white;
        ///    margin-left: 1rem;
        ///    background-color: #2c2f33;
        ///    border-radius: 2rem;
        ///    margin-top: 1rem;
        ///    width: 100%;
        ///    align-items: center;
        ///  &quot;
        ///&gt;
        ///  &lt;img
        ///    src=&quot;{item.profile}&quot;
        ///    aria-hidden=&quot;true&quot;
        ///    alt=&quot;&quot;
        ///    style=&quot;
        ///      margin-left: 0.75rem;
        ///      width: 50px;
        ///      height: 50px;
        ///      border-radius: 50%;
        ///      overflow: hidden;
        ///      cursor: pointer;
        ///      -webkit-user-select: none;
        ///      -moz-user-sele [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ticketItem {
            get {
                return ResourceManager.GetString("ticketItem", resourceCulture);
            }
        }
    }
}
